version: '3.8'

services:
  coin-gems:
    build: .
    container_name: upbit-coin-gems
    restart: unless-stopped
    environment:
      # .env 파일에서 환경변수 로드 (선택사항)
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    volumes:
      # .env 파일 마운트 (API 키 사용시)
      - ./.env:/app/.env:ro
    # 네트워크 설정 (API 호출용)
    network_mode: "host"
    # 메모리 제한 (선택사항)
    mem_limit: 512m
    # CPU 제한 (선택사항) 
    cpus: 0.5
    
  # 웹 인터페이스용 (추후 확장)
  coin-gems-web:
    build: .
    container_name: upbit-coin-gems-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    volumes:
      - ./.env:/app/.env:ro
    command: ["python", "main.py", "--web"]
    profiles:
      - web  # 웹 모드는 선택적으로 실행
    mem_limit: 512m
    cpus: 0.5 